# Run Configuration
name: "test_run"
normalize: True
smoothing_sigma: 1.5

trajectory_file: "config/trajectory_z.yaml"
sonar_config_file: "config/sonar_config.yaml"
scene_file: "scenes/test.ply"

output_folder: "output/"