# Trajectory from start to end with given total_time and timesteps
start_pose:
  position: [0, 0, 0]
  rotation_euler: [0, 0, 0]  # roll, pitch, yaw in degrees

end_pose:
  position: [0, 0, -20]
  rotation_euler: [0, 0, 0]  # yaw rotated 90 degrees

total_time: 10.0
timesteps: 30